package flapjack.gui.navpanel;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import flapjack.gui.*;

import scri.commons.gui.*;

public class NBStartHelpPanel extends javax.swing.JPanel
{
	private JLabel[] labels = new JLabel[8];

	private static String home =
		"http://bioinf.scri.ac.uk/flapjack/help";

    public NBStartHelpPanel()
	{
		initComponents();
		setOpaque(false);

		RB.setText(homeLabel, "gui.navpanel.NBStartHelpPanel.homeLabel");

		ClickListener clicker = new ClickListener();

		homeLabel.setIcon(Icons.getIcon("BOOK"));
		homeLabel.setCursor(FlapjackUtils.HAND_CURSOR);
		homeLabel.addMouseListener(clicker);

		labels[0] = link1; labels[1] = link2;
		labels[2] = link3; labels[3] = link4;
		labels[4] = link5; labels[5] = link6;
		labels[6] = link7; labels[7] = link8;

		for (int i = 0; i < labels.length; i++)
		{
			RB.setText(labels[i], "gui.navpanel.NBStartHelpPanel.link" + (i+1));
			labels[i].setCursor(FlapjackUtils.HAND_CURSOR);
			labels[i].addMouseListener(clicker);
		}
    }

    private class ClickListener extends MouseAdapter
    {
    	public void mouseClicked(MouseEvent e)
    	{
    		if (e.getSource() == homeLabel)
    			FlapjackUtils.visitURL(home);

    		else
    		{
    			for (int i = 0; i < labels.length; i++)
    				if (e.getSource() == labels[i])
    				{
    					FlapjackUtils.visitURL(RB.getString(
    						"gui.navpanel.NBStartHelpPanel.url" + (i+1)));;
    				}
    		}
    	}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeLabel = new javax.swing.JLabel();
        link1 = new javax.swing.JLabel();
        link2 = new javax.swing.JLabel();
        link3 = new javax.swing.JLabel();
        link4 = new javax.swing.JLabel();
        link5 = new javax.swing.JLabel();
        link6 = new javax.swing.JLabel();
        link7 = new javax.swing.JLabel();
        link8 = new javax.swing.JLabel();

        homeLabel.setForeground(new java.awt.Color(68, 106, 156));
        homeLabel.setText("Visit the online Flapjack user manual");

        link1.setForeground(new java.awt.Color(68, 106, 156));
        link1.setIcon(Icons.getIcon("BUTTON"));
        link1.setText("link1");

        link2.setForeground(new java.awt.Color(68, 106, 156));
        link2.setIcon(Icons.getIcon("BUTTON"));
        link2.setText("link2");

        link3.setForeground(new java.awt.Color(68, 106, 156));
        link3.setIcon(Icons.getIcon("BUTTON"));
        link3.setText("link3");

        link4.setForeground(new java.awt.Color(68, 106, 156));
        link4.setIcon(Icons.getIcon("BUTTON"));
        link4.setText("link4");

        link5.setForeground(new java.awt.Color(68, 106, 156));
        link5.setIcon(Icons.getIcon("BUTTON"));
        link5.setText("link5");

        link6.setForeground(new java.awt.Color(68, 106, 156));
        link6.setIcon(Icons.getIcon("BUTTON"));
        link6.setText("link6");

        link7.setForeground(new java.awt.Color(68, 106, 156));
        link7.setIcon(Icons.getIcon("BUTTON"));
        link7.setText("link7");

        link8.setForeground(new java.awt.Color(68, 106, 156));
        link8.setIcon(Icons.getIcon("BUTTON"));
        link8.setText("link8");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(homeLabel)
                    .add(link2)
                    .add(link1)
                    .add(link3)
                    .add(link4)
                    .add(link5)
                    .add(link6)
                    .add(link7)
                    .add(link8))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(homeLabel)
                .add(18, 18, 18)
                .add(link1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link8)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel link1;
    private javax.swing.JLabel link2;
    private javax.swing.JLabel link3;
    private javax.swing.JLabel link4;
    private javax.swing.JLabel link5;
    private javax.swing.JLabel link6;
    private javax.swing.JLabel link7;
    private javax.swing.JLabel link8;
    // End of variables declaration//GEN-END:variables

}
