package flapjack.gui.dialog.prefs;

import javax.swing.*;

import flapjack.gui.*;

class NBWarningPanel extends JPanel implements IPrefsTab
{
	public NBWarningPanel()
    {
        initComponents();

		warnDuplicateMarkers.setText(RB.getString("gui.dialog.prefs.NBWarningPanel.warnDuplicateMarkers"));
		RB.setMnemonic(warnDuplicateMarkers, "gui.dialog.prefs.NBWarningPanel.warnDuplicateMarkers");

		initSettings();
    }

    private void initSettings()
    {
    	warnDuplicateMarkers.setSelected(Prefs.warnDuplicateMarkers);
    }

	public void applySettings()
	{
		Prefs.warnDuplicateMarkers = warnDuplicateMarkers.isSelected();
	}

	public void setDefaults()
	{
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warnDuplicateMarkers = new javax.swing.JCheckBox();

        warnDuplicateMarkers.setText("Warn when duplicate markers are found during data import");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(warnDuplicateMarkers)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(warnDuplicateMarkers)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox warnDuplicateMarkers;
    // End of variables declaration//GEN-END:variables
}