package flapjack.gui.navpanel;

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.*;

import flapjack.gui.*;

public class NBStartFilePanel extends javax.swing.JPanel
{
	private JLabel[] labels = new JLabel[4];
	private String[] files = new String[4];

	public NBStartFilePanel()
	{
		initComponents();
		setOpaque(false);

		RB.setText(importLabel, "gui.navpanel.NBStartFilePanel.importLabel");
		RB.setText(openLabel, "gui.navpanel.NBStartFilePanel.openLabel");

		ClickListener clicker = new ClickListener();

		importLabel.setIcon(Icons.getIcon("FILEIMPORT"));
		importLabel.addMouseListener(clicker);
		importLabel.setCursor(FlapjackUtils.HAND_CURSOR);

		// Create the labels array
		labels[0] = project0; labels[1] = project1;
		labels[2] = project2; labels[3] = project3;

		// Create the files array
		files[0] = Prefs.guiRecentProject1; files[1] = Prefs.guiRecentProject2;
		files[2] = Prefs.guiRecentProject3; files[3] = Prefs.guiRecentProject4;

		for (int i = 0; i < labels.length; i++)
		{
			if (files[i] != null)
			{
				labels[i].addMouseListener(clicker);
				labels[i].setCursor(FlapjackUtils.HAND_CURSOR);
				labels[i].setText(files[i]);
			}
			else
				labels[i].setVisible(false);
		}
    }

    class ClickListener extends MouseAdapter
    {
    	public void mouseClicked(MouseEvent e)
    	{
    		WinMain wm = Flapjack.winMain;

    		if (e.getSource() == importLabel)
				wm.mFile.fileImport();

			for (int i = 0; i < labels.length; i++)
				if (e.getSource() == labels[i])
					wm.mFile.fileOpen(new File(files[i]));
    	}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importLabel = new javax.swing.JLabel();
        openLabel = new javax.swing.JLabel();
        project0 = new javax.swing.JLabel();
        project1 = new javax.swing.JLabel();
        project2 = new javax.swing.JLabel();
        project3 = new javax.swing.JLabel();

        importLabel.setForeground(new java.awt.Color(68, 106, 156));
        importLabel.setText("Import data into Flapjack");

        openLabel.setText("Open an previously accessed Flapjack project:");

        project0.setForeground(new java.awt.Color(68, 106, 156));
        project0.setIcon(Icons.getIcon("FLAPJACK16"));
        project0.setText("<project0>");

        project1.setForeground(new java.awt.Color(68, 106, 156));
        project1.setIcon(Icons.getIcon("FLAPJACK16"));
        project1.setText("<project1>");

        project2.setForeground(new java.awt.Color(68, 106, 156));
        project2.setIcon(Icons.getIcon("FLAPJACK16"));
        project2.setText("<project2>");

        project3.setForeground(new java.awt.Color(68, 106, 156));
        project3.setIcon(Icons.getIcon("FLAPJACK16"));
        project3.setText("<project3>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(importLabel)
                    .add(openLabel)
                    .add(project0)
                    .add(project1)
                    .add(project2)
                    .add(project3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(importLabel)
                .add(18, 18, 18)
                .add(openLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(project0)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(project1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(project2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(project3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel importLabel;
    private javax.swing.JLabel openLabel;
    private javax.swing.JLabel project0;
    private javax.swing.JLabel project1;
    private javax.swing.JLabel project2;
    private javax.swing.JLabel project3;
    // End of variables declaration//GEN-END:variables

}
