package flapjack.gui.dialog;

import flapjack.data.*;
import flapjack.gui.*;

class NBSelectTraitsPanel extends javax.swing.JPanel
{
	private GTViewSet viewSet;

	public NBSelectTraitsPanel(GTViewSet viewSet)
	{
		initComponents();

		this.viewSet = viewSet;

		RB.setText(label, "gui.dialog.NBSelectTraitsPanel.label");
		traitLabel1.setText(RB.format("gui.dialog.NBSelectTraitsPanel.trait", 1));
		traitLabel1.setDisplayedMnemonic('1');
		traitLabel2.setText(RB.format("gui.dialog.NBSelectTraitsPanel.trait", 2));
		traitLabel2.setDisplayedMnemonic('2');
		traitLabel3.setText(RB.format("gui.dialog.NBSelectTraitsPanel.trait", 3));
		traitLabel3.setDisplayedMnemonic('3');
		RB.setText(hintLabel, "gui.dialog.NBSelectTraitsPanel.hintLabel");

		// Add an "empty" trait at the top of each list
		trait1.addItem("");
		trait2.addItem("");
		trait3.addItem("");

		// Add all the real traits
		for (Trait t: viewSet.getDataSet().getTraits())
		{
			trait1.addItem(t.getName());
			trait2.addItem(t.getName());
			trait3.addItem(t.getName());
		}

		// Set the currently selected index for each combo box to be the trait
		// index for that column from the viewSet (+1 to deal with the empty)
		trait1.setSelectedIndex(viewSet.getTraits()[0]+1);
		trait2.setSelectedIndex(viewSet.getTraits()[1]+1);
		trait3.setSelectedIndex(viewSet.getTraits()[2]+1);
	}

	void isOK()
	{
		viewSet.setTraits(new int[] {
			trait1.getSelectedIndex() - 1,
			trait2.getSelectedIndex() - 1,
			trait3.getSelectedIndex() - 1
		});
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        traitLabel1 = new javax.swing.JLabel();
        trait1 = new javax.swing.JComboBox();
        traitLabel2 = new javax.swing.JLabel();
        trait2 = new javax.swing.JComboBox();
        traitLabel3 = new javax.swing.JLabel();
        trait3 = new javax.swing.JComboBox();
        hintLabel = new javax.swing.JLabel();

        label.setText("The traits heatmap can display up to three different traits (one per column):");

        traitLabel1.setLabelFor(trait1);
        traitLabel1.setText("Trait 1:");

        traitLabel2.setLabelFor(trait2);
        traitLabel2.setText("Trait 2:");

        traitLabel3.setLabelFor(trait3);
        traitLabel3.setText("Trait 3:");

        hintLabel.setText("(You can also right-click on the heatmap to quickly set a trait)");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(label)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(traitLabel1)
                            .add(traitLabel2)
                            .add(traitLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(trait2, 0, 320, Short.MAX_VALUE)
                            .add(trait1, 0, 320, Short.MAX_VALUE)
                            .add(trait3, 0, 320, Short.MAX_VALUE)))
                    .add(hintLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(label)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(traitLabel1)
                    .add(trait1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(traitLabel2)
                    .add(trait2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(traitLabel3)
                    .add(trait3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(hintLabel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel label;
    private javax.swing.JComboBox trait1;
    private javax.swing.JComboBox trait2;
    private javax.swing.JComboBox trait3;
    private javax.swing.JLabel traitLabel1;
    private javax.swing.JLabel traitLabel2;
    private javax.swing.JLabel traitLabel3;
    // End of variables declaration//GEN-END:variables
}