package flapjack.gui.dialog;

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.*;

import flapjack.gui.*;

import scri.commons.gui.*;

public class NBDataImportPanel extends javax.swing.JPanel implements ActionListener
{
	public NBDataImportPanel()
	{
		initComponents();

		mapButton.addActionListener(this);
		genoButton.addActionListener(this);

//		mapText.setText("data\\illumina.map");
//		genoText.setText("data\\illumina.data");

		// Apply localized text
		mapLabel.setText(RB.getString("gui.dialog.NBDataImportPanel.mapLabel"));
		mapButton.setText(RB.getString("gui.text.browse"));
		genoLabel.setText(RB.getString("gui.dialog.NBDataImportPanel.genoLabel"));
		genoButton.setText(RB.getString("gui.text.browse"));
	}

	public void actionPerformed(ActionEvent e)
	{
		if (e.getSource() == mapButton)
			browse(mapText);

		else if (e.getSource() == genoButton)
			browse(genoText);
	}

	private void browse(JTextField textfield)
	{
		JFileChooser fc = new JFileChooser();
		fc.setDialogTitle(RB.getString("gui.dialog.NBDataImportPanel.fcTitle"));
		fc.setCurrentDirectory(new File(Prefs.guiCurrentDir));

		if (textfield.getText().length() > 0)
			fc.setCurrentDirectory(new File(textfield.getText()));

//		Filters.setFilters(fc, -1, FAS, PHY_S, PHY_I, ALN, MSF, NEX, NEX_B);

		if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
		{
			File file = fc.getSelectedFile();
			Prefs.guiCurrentDir = fc.getCurrentDirectory().toString();

			textfield.setText(file.toString());
		}
	}

	boolean isOK()
	{
		if (mapText.getText().length() == 0 || genoText.getText().length() == 0)
		{
			TaskDialog.warning(
				RB.getString("gui.dialog.NBDataImportPanel.warn1"),
				RB.getString("gui.text.ok"));
			return false;
		}

		return true;
	}

	File getMapFile()
	{
		return new File(mapText.getText());
	}

	File getGenotypeFile()
	{
		return new File(genoText.getText());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mapLabel = new javax.swing.JLabel();
        mapText = new javax.swing.JTextField();
        mapButton = new javax.swing.JButton();
        genoLabel = new javax.swing.JLabel();
        genoText = new javax.swing.JTextField();
        genoButton = new javax.swing.JButton();

        mapLabel.setDisplayedMnemonic('m');
        mapLabel.setLabelFor(mapText);
        mapLabel.setText("Map file:");

        mapButton.setText("Browse...");

        genoLabel.setDisplayedMnemonic('g');
        genoLabel.setLabelFor(genoText);
        genoLabel.setText("Genotype file:");

        genoButton.setText("Browse...");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(genoLabel)
                    .add(mapLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(genoText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .add(mapText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mapButton)
                    .add(genoButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(mapLabel)
                    .add(mapButton)
                    .add(mapText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(genoLabel)
                    .add(genoButton)
                    .add(genoText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton genoButton;
    private javax.swing.JLabel genoLabel;
    private javax.swing.JTextField genoText;
    private javax.swing.JButton mapButton;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JTextField mapText;
    // End of variables declaration//GEN-END:variables

}