package flapjack.gui.dialog;

import java.awt.*;
import java.awt.event.*;
import java.lang.reflect.*;
import java.net.*;
import javax.swing.*;

import flapjack.gui.*;

import scri.commons.gui.*;

class NBFindPanel extends JPanel implements ActionListener
{
	NBFindPanel()
	{
		initComponents();

		link.setIcon(Icons.WEB);

		findLabel.setText(RB.getString("gui.dialog.NBFindPanel.findLabel"));
		searchLabel.setText(RB.getString("gui.dialog.NBFindPanel.searchLabel"));
		panel.setBorder(BorderFactory.createTitledBorder(
			RB.getString("gui.dialog.NBFindPanel.panelTitle")));
		foundLabel1.setText(RB.getString("gui.dialog.NBFindPanel.foundLabel1"));
		foundLabel2.setText("");

		checkChromo.setText(RB.getString("gui.dialog.NBFindPanel.checkChromo"));
		checkChromo.setSelected(Prefs.guiFindAllChromo);
		checkChromo.setEnabled(Prefs.guiFindMethod == 1);
		checkChromo.addActionListener(this);
		checkChromo.setVisible(false);
		checkCase.setText(RB.getString("gui.dialog.NBFindPanel.checkCase"));
		checkCase.setSelected(Prefs.guiFindMatchCase);
		checkCase.addActionListener(this);
		checkRegular.setText(RB.getString("gui.dialog.NBFindPanel.checkRegular"));
		checkRegular.setSelected(Prefs.guiFindUseRegex);
		checkRegular.addActionListener(this);

		searchCombo.addItem(RB.getString("gui.dialog.NBFindPanel.lines"));
		searchCombo.addItem(RB.getString("gui.dialog.NBFindPanel.markers"));
		searchCombo.setSelectedIndex(Prefs.guiFindMethod);
		searchCombo.addActionListener(this);

		initLinkLabel();
	}

	public void actionPerformed(ActionEvent e)
	{
		checkChromo.setEnabled(searchCombo.getSelectedIndex() == 1);

		Prefs.guiFindAllChromo = checkChromo.isSelected();
		Prefs.guiFindMatchCase = checkCase.isSelected();
		Prefs.guiFindUseRegex = checkRegular.isSelected();
		Prefs.guiFindMethod = searchCombo.getSelectedIndex();
	}

	private void initLinkLabel()
	{
		String html = "http://java.sun.com/javase/6/docs/api/java/util/regex/Pattern.html";
		boolean makeLinkLabel = true;

		// Turns the label into a blue mouse-over clickable link to a website
		link.setText(RB.getString("gui.dialog.NBFindPanel.link"));
		link.setForeground(Color.blue);
		link.setCursor(new Cursor(Cursor.HAND_CURSOR));

		if (SystemUtils.isMacOS())
			makeJava5OSXLinkLabel(html);
		else
			makeJava6LinkLabel(html);
	}

	// Active the link using the Java 6 Desktop support object
	private void makeJava6LinkLabel(final String html)
	{
		link.addMouseListener(new MouseAdapter()
		{
			public void mouseClicked(MouseEvent event)
			{
				try
				{
					Desktop desktop = Desktop.getDesktop();

		        	URI uri = new URI(html);
		        	desktop.browse(uri);
				}
				catch (Exception e) {}
			}
		});
	}

	// Active the link using OSX Java 5 compatible code
	// See: http://www.centerkey.com/java/browser/
	private void makeJava5OSXLinkLabel(final String html)
	{
		link.addMouseListener(new MouseAdapter()
		{
			public void mouseClicked(MouseEvent event)
			{
				try
				{
					Class<?> fileMgr = Class.forName("com.apple.eio.FileManager");
					Method openURL = fileMgr.getDeclaredMethod("openURL",
						new Class[] {String.class});

					openURL.invoke(null, new Object[] {html});
				}
				catch (Exception e) {}
			}
		});
	}

	String getSearchStr()
	{
		String str = (String) findCombo.getSelectedItem();

		if (str == null)
			return "";
		else
			return str;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findLabel = new javax.swing.JLabel();
        findCombo = new javax.swing.JComboBox();
        searchLabel = new javax.swing.JLabel();
        searchCombo = new javax.swing.JComboBox();
        panel = new javax.swing.JPanel();
        checkChromo = new javax.swing.JCheckBox();
        checkRegular = new javax.swing.JCheckBox();
        link = new javax.swing.JLabel();
        checkCase = new javax.swing.JCheckBox();
        foundLabel1 = new javax.swing.JLabel();
        foundLabel2 = new javax.swing.JLabel();

        findLabel.setDisplayedMnemonic('f');
        findLabel.setLabelFor(findCombo);
        findLabel.setText("Find what:");

        findCombo.setEditable(true);

        searchLabel.setDisplayedMnemonic('s');
        searchLabel.setLabelFor(searchCombo);
        searchLabel.setText("Search within:");

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options:"));

        checkChromo.setMnemonic('c');
        checkChromo.setText("Search across all chromosomes");
        checkChromo.setDisplayedMnemonicIndex(18);

        checkRegular.setMnemonic('r');
        checkRegular.setText("Use regular expression pattern matching");

        link.setText("View information on searching using regular expressions");

        checkCase.setMnemonic('m');
        checkCase.setText("Match case");

        org.jdesktop.layout.GroupLayout panelLayout = new org.jdesktop.layout.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(checkChromo)
                    .add(checkCase)
                    .add(panelLayout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(link))
                    .add(checkRegular))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(checkChromo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(checkCase)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(checkRegular)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        foundLabel1.setText("Search result:");

        foundLabel2.setText("<>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(searchLabel)
                            .add(findLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(findCombo, 0, 249, Short.MAX_VALUE)
                            .add(searchCombo, 0, 249, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(foundLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(foundLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(findLabel)
                    .add(findCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchLabel)
                    .add(searchCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(foundLabel1)
                    .add(foundLabel2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkCase;
    private javax.swing.JCheckBox checkChromo;
    private javax.swing.JCheckBox checkRegular;
    javax.swing.JComboBox findCombo;
    private javax.swing.JLabel findLabel;
    private javax.swing.JLabel foundLabel1;
    javax.swing.JLabel foundLabel2;
    private javax.swing.JLabel link;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox searchCombo;
    private javax.swing.JLabel searchLabel;
    // End of variables declaration//GEN-END:variables
}