package flapjack.gui.dialog;

import javax.swing.*;

import flapjack.data.*;
import flapjack.gui.*;

import scri.commons.gui.*;

class NBHideMarkersPanel extends JPanel
{
	public NBHideMarkersPanel(HideMarkersDialog dialog, GTView view)
	{
		initComponents();

		int total = view.getMarkerCount();
		int selected = view.getSelectedMarkerCount();
		int unselected = total - selected;

		rHideSelected.setText(RB.format("gui.dialog.NBHideMarkersDialog.rHideSelected", selected, total));
		rHideUnselected.setText(RB.format("gui.dialog.NBHideMarkersDialog.rHideUnselected", unselected, total));
		RB.setMnemonic(rHideSelected, "gui.dialog.NBHideMarkersDialog.rHideSelected");
		RB.setMnemonic(rHideUnselected, "gui.dialog.NBHideMarkersDialog.rHideUnselected");

		hidePanel.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.NBHideMarkersDialog.hidePanel.title")));
		RB.setText(hideLabel, "gui.dialog.NBHideMarkersDialog.hideLabel");
		showPanel.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.NBHideMarkersDialog.showPanel.title")));
		RB.setText(showLabel, "gui.dialog.NBHideMarkersDialog.showLabel");
		RB.setText(bRestore, "gui.dialog.NBHideMarkersDialog.bRestore");

		if (SystemUtils.isMacOS())
			RB.setText(hideHint, "gui.dialog.NBHideMarkersDialog.hideHintOSX");
		else
			RB.setText(hideHint, "gui.dialog.NBHideMarkersDialog.hideHint");
		countLabel.setText(RB.format("gui.dialog.NBHideMarkersDialog.countLabel", view.getHiddenMarkerCount()));

		rHideSelected.setSelected(Prefs.guiHideSelectedMarkers);
		rHideUnselected.setSelected(!Prefs.guiHideSelectedMarkers);

		bRestore.addActionListener(dialog);
		if (view.getHiddenMarkerCount() == 0)
			bRestore.setEnabled(false);
	}

	void isOK()
	{
		Prefs.guiHideSelectedMarkers = rHideSelected.isSelected();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        hidePanel = new javax.swing.JPanel();
        rHideUnselected = new javax.swing.JRadioButton();
        rHideSelected = new javax.swing.JRadioButton();
        hideLabel = new javax.swing.JLabel();
        hideHint = new javax.swing.JLabel();
        showPanel = new javax.swing.JPanel();
        showLabel = new javax.swing.JLabel();
        bRestore = new javax.swing.JButton();
        countLabel = new javax.swing.JLabel();

        hidePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hide markers:"));

        buttonGroup1.add(rHideUnselected);
        rHideUnselected.setText("Hide all the markers that are NOT currently selected");

        buttonGroup1.add(rHideSelected);
        rHideSelected.setText("Hide all the markers that ARE currently selected");

        hideLabel.setText("Note that the last available marker in the chromosome can never be set to hidden");

        hideHint.setText("(You can also use CTRL double-click (in Marker Mode) to hide individual markers)");

        org.jdesktop.layout.GroupLayout hidePanelLayout = new org.jdesktop.layout.GroupLayout(hidePanel);
        hidePanel.setLayout(hidePanelLayout);
        hidePanelLayout.setHorizontalGroup(
            hidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(hidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(hidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rHideSelected)
                    .add(rHideUnselected)
                    .add(hideLabel)
                    .add(hideHint))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hidePanelLayout.setVerticalGroup(
            hidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(hidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(hideLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(rHideUnselected)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rHideSelected)
                .add(18, 18, 18)
                .add(hideHint)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Show markers:"));

        showLabel.setText("Click to restore all currently hidden markers to the view:");

        bRestore.setText("Show hidden markers");

        countLabel.setText("(0 currently hidden)");

        org.jdesktop.layout.GroupLayout showPanelLayout = new org.jdesktop.layout.GroupLayout(showPanel);
        showPanel.setLayout(showPanelLayout);
        showPanelLayout.setHorizontalGroup(
            showPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(showPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(showPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(showLabel)
                    .add(showPanelLayout.createSequentialGroup()
                        .add(bRestore)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(countLabel)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        showPanelLayout.setVerticalGroup(
            showPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(showPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(showLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(showPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bRestore)
                    .add(countLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, showPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, hidePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(hidePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(showPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton bRestore;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel countLabel;
    private javax.swing.JLabel hideHint;
    private javax.swing.JLabel hideLabel;
    private javax.swing.JPanel hidePanel;
    private javax.swing.JRadioButton rHideSelected;
    private javax.swing.JRadioButton rHideUnselected;
    private javax.swing.JLabel showLabel;
    private javax.swing.JPanel showPanel;
    // End of variables declaration//GEN-END:variables
}