// Copyright 2007-2010 Plant Bioinformatics Group, SCRI. All rights reserved.
// Use is subject to the accompanying licence terms.

package flapjack.gui.dialog;

import java.awt.*;
import javax.swing.*;

import flapjack.data.*;
import flapjack.gui.*;

import scri.commons.gui.*;

/**
 * This dialog handles BOTH lines and markers - hence all the if statements. But
 * it's still quicker/easier to just combine it all into a single class, rather
 * than having two practically identical (but separate) classes.
 */
class NBHideLMPanel extends JPanel
{
	private String i18n;

	public NBHideLMPanel(HideLMDialog dialog, GTView view, boolean markers)
	{
		initComponents();

		setBackground((Color)UIManager.get("fjDialogBG"));
		hidePanel.setBackground((Color)UIManager.get("fjDialogBG"));
		showPanel.setBackground((Color)UIManager.get("fjDialogBG"));

		i18n = markers ? "markers" : "lines";

		int total, selected, unselected;

		if (i18n.equals("markers"))
		{
			total = view.getMarkerCount();
			selected = view.countSelectedMarkers();
		}
		else
		{
			total = view.getLineCount();
			selected = view.countSelectedLines();
		}

		unselected = total - selected;

		rHideSelected.setText(RB.format("gui.dialog.NBHideLMPanel." + i18n + ".rHideSelected", selected, total));
		rHideUnselected.setText(RB.format("gui.dialog.NBHideLMPanel." + i18n + ".rHideUnselected", unselected, total));
		RB.setMnemonic(rHideSelected, "gui.dialog.NBHideLMPanel." + i18n + ".rHideSelected");
		RB.setMnemonic(rHideUnselected, "gui.dialog.NBHideLMPanel." + i18n + ".rHideUnselected");

		hidePanel.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.NBHideLMPanel." + i18n + ".hidePanel.title")));
		RB.setText(hideLabel, "gui.dialog.NBHideLMPanel." + i18n + ".hideLabel");
		showPanel.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.NBHideLMPanel." + i18n + ".showPanel.title")));
		RB.setText(showLabel, "gui.dialog.NBHideLMPanel." + i18n + ".showLabel");
		RB.setText(bRestore, "gui.dialog.NBHideLMPanel." + i18n + ".bRestore");

		if (SystemUtils.isMacOS())
			hideHint.setText(
				RB.format("gui.dialog.NBHideLMPanel." + i18n + ".hideHintOSX",
				RB.getString("gui.StatusBar.cmnd")));
		else
			RB.setText(hideHint, "gui.dialog.NBHideLMPanel." + i18n + ".hideHint");

		if (i18n.equals("markers"))
		{
			rHideSelected.setSelected(Prefs.guiHideSelectedMarkers);
			rHideUnselected.setSelected(!Prefs.guiHideSelectedMarkers);
			countLabel.setText(RB.format("gui.dialog.NBHideLMPanel.countLabel",
				view.hiddenMarkerCount()));

			if (view.hiddenMarkerCount() == 0)
				bRestore.setEnabled(false);
		}
		else
		{
			rHideSelected.setSelected(Prefs.guiHideSelectedLines);
			rHideUnselected.setSelected(!Prefs.guiHideSelectedLines);
			countLabel.setText(RB.format("gui.dialog.NBHideLMPanel.countLabel",
				view.hiddenLineCount()));

			if (view.hiddenLineCount() == 0)
				bRestore.setEnabled(false);
		}

		bRestore.addActionListener(dialog);
	}

	void isOK()
	{
		if (i18n.equals("markers"))
			Prefs.guiHideSelectedMarkers = rHideSelected.isSelected();
		else
			Prefs.guiHideSelectedLines = rHideSelected.isSelected();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        hidePanel = new javax.swing.JPanel();
        rHideUnselected = new javax.swing.JRadioButton();
        rHideSelected = new javax.swing.JRadioButton();
        hideLabel = new javax.swing.JLabel();
        hideHint = new javax.swing.JLabel();
        showPanel = new javax.swing.JPanel();
        showLabel = new javax.swing.JLabel();
        bRestore = new javax.swing.JButton();
        countLabel = new javax.swing.JLabel();

        hidePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hide markers:"));

        buttonGroup1.add(rHideUnselected);
        rHideUnselected.setText("Hide all the markers that are NOT currently selected");

        buttonGroup1.add(rHideSelected);
        rHideSelected.setText("Hide all the markers that ARE currently selected");

        hideLabel.setText("hideLabel");

        hideHint.setText("hideHint");

        org.jdesktop.layout.GroupLayout hidePanelLayout = new org.jdesktop.layout.GroupLayout(hidePanel);
        hidePanel.setLayout(hidePanelLayout);
        hidePanelLayout.setHorizontalGroup(
            hidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(hidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(hidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rHideSelected)
                    .add(rHideUnselected)
                    .add(hideLabel)
                    .add(hideHint))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hidePanelLayout.setVerticalGroup(
            hidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(hidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(hideLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(rHideUnselected)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rHideSelected)
                .add(18, 18, 18)
                .add(hideHint)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Show markers:"));

        showLabel.setText("Click to restore all currently hidden markers to the view:");

        bRestore.setText("Show hidden markers");

        countLabel.setText("(0 currently hidden)");

        org.jdesktop.layout.GroupLayout showPanelLayout = new org.jdesktop.layout.GroupLayout(showPanel);
        showPanel.setLayout(showPanelLayout);
        showPanelLayout.setHorizontalGroup(
            showPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(showPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(showPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(showLabel)
                    .add(showPanelLayout.createSequentialGroup()
                        .add(bRestore)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(countLabel)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        showPanelLayout.setVerticalGroup(
            showPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(showPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(showLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(showPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bRestore)
                    .add(countLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, showPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, hidePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(hidePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(showPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton bRestore;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel countLabel;
    private javax.swing.JLabel hideHint;
    private javax.swing.JLabel hideLabel;
    private javax.swing.JPanel hidePanel;
    private javax.swing.JRadioButton rHideSelected;
    private javax.swing.JRadioButton rHideUnselected;
    private javax.swing.JLabel showLabel;
    private javax.swing.JPanel showPanel;
    // End of variables declaration//GEN-END:variables
}