package flapjack.gui.dialog;

import java.awt.*;
import javax.swing.*;

import scri.commons.gui.*;

import flapjack.data.*;
import flapjack.gui.*;
import flapjack.gui.visualization.*;

public class NBSelectGraphPanel extends javax.swing.JPanel
{
    /** Creates new form NBSelectGraphPanel */
    public NBSelectGraphPanel(GenotypePanel gPanel)
	{
        initComponents();

		setBackground((Color)UIManager.get("fjDialogBG"));

		ChromosomeMap map = gPanel.getView().getChromosomeMap();

		// Add the names to the combo box
		for (GraphData graph: map.getGraphs())
			graphSelectCombo.addItem(graph.getName());

		// And select whichever one is "selected"
		graphSelectCombo.setSelectedIndex(gPanel.getViewSet().getGraphIndex());


		graphTypeCombo.addItem(RB.getString("gui.dialog.NBSelectGraphDialog.histogramGraphType"));
		graphTypeCombo.addItem(RB.getString("gui.dialog.NBSelectGraphDialog.lineGraphType"));
		graphTypeCombo.setSelectedIndex(Prefs.guiGraphStyle);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGraphSelect = new javax.swing.JLabel();
        graphSelectCombo = new javax.swing.JComboBox();
        lblGraphType = new javax.swing.JLabel();
        graphTypeCombo = new javax.swing.JComboBox();

        lblGraphSelect.setLabelFor(graphSelectCombo);
        lblGraphSelect.setText("Graph to display:");

        lblGraphType.setText("Graph type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGraphSelect)
                    .addComponent(lblGraphType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphTypeCombo, 0, 294, Short.MAX_VALUE)
                    .addComponent(graphSelectCombo, 0, 294, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraphSelect)
                    .addComponent(graphSelectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraphType)
                    .addComponent(graphTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JComboBox graphSelectCombo;
    javax.swing.JComboBox graphTypeCombo;
    javax.swing.JLabel lblGraphSelect;
    javax.swing.JLabel lblGraphType;
    // End of variables declaration//GEN-END:variables

}
