// Copyright 2007-2009 Plant Bioinformatics Group, SCRI. All rights reserved.
// Use is subject to the accompanying licence terms.

package flapjack.gui.dialog.prefs;

import java.awt.*;
import javax.swing.*;

import flapjack.gui.*;

import scri.commons.gui.*;

class NBWebPanel extends JPanel implements IPrefsTab
{
	public NBWebPanel()
    {
        initComponents();

        setBackground((Color)UIManager.get("fjDialogBG"));
        panel.setBackground((Color)UIManager.get("fjDialogBG"));

		panel.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.prefs.NBWebPanel.panelTitle")));
		RB.setText(checkProxy, "gui.dialog.prefs.NBWebPanel.checkProxy");
		RB.setText(labelAddress, "gui.dialog.prefs.NBWebPanel.labelAddress");
		RB.setText(labelPort, "gui.dialog.prefs.NBWebPanel.labelPort");
		RB.setText(labelUsername, "gui.dialog.prefs.NBWebPanel.labelUsername");
		RB.setText(labelPassword, "gui.dialog.prefs.NBWebPanel.labelPassword");

		initSettings();
    }

    private void initSettings()
    {
    	checkProxy.setSelected(Prefs.proxyUse);

		proxyAddress.setText(Prefs.proxyAddress);
		proxyPort.setValue(Prefs.proxyPort);
		proxyUsername.setText(Prefs.proxyUsername);
		proxyPassword.setText(Prefs.proxyPassword);

		try
		{
			java.net.URL url = new java.net.URL("http://www.bbc.co.uk");
			java.net.HttpURLConnection c = (java.net.HttpURLConnection) url.openConnection();

			int code = c.getResponseCode();
			c.disconnect();

			System.out.println("response: " + code);
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
    }

	public void applySettings()
	{
		Prefs.proxyUse = checkProxy.isSelected();

		Prefs.proxyAddress = proxyAddress.getText();
		Prefs.proxyPort = (Integer) proxyPort.getValue();
		Prefs.proxyUsername = proxyUsername.getText();
		Prefs.proxyPassword = new String(proxyPassword.getPassword());

		Flapjack.setProxy();
	}

	public void setDefaults()
	{
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        checkProxy = new javax.swing.JCheckBox();
        labelAddress = new javax.swing.JLabel();
        proxyAddress = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        proxyUsername = new javax.swing.JTextField();
        labelPort = new javax.swing.JLabel();
        proxyPort = new javax.swing.JSpinner();
        labelPassword = new javax.swing.JLabel();
        proxyPassword = new javax.swing.JPasswordField();

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Internet settings:"));

        checkProxy.setText("Use a proxy server for internet connectivity");

        labelAddress.setLabelFor(proxyAddress);
        labelAddress.setText("Address:");

        labelUsername.setLabelFor(proxyUsername);
        labelUsername.setText("Username:");

        labelPort.setLabelFor(proxyPort);
        labelPort.setText("Port:");

        proxyPort.setModel(new javax.swing.SpinnerNumberModel(8080, 1, 65535, 1));

        labelPassword.setLabelFor(proxyPassword);
        labelPassword.setText("Password:");

        org.jdesktop.layout.GroupLayout panelLayout = new org.jdesktop.layout.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(checkProxy)
                .addContainerGap(146, Short.MAX_VALUE))
            .add(panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelPassword)
                    .add(labelUsername)
                    .add(labelAddress))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(proxyPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .add(proxyUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .add(proxyAddress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(labelPort)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(proxyPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelLayout.linkSize(new java.awt.Component[] {proxyAddress, proxyPassword, proxyUsername}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(checkProxy)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelAddress)
                    .add(proxyAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(proxyPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelPort))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelUsername)
                    .add(proxyUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelPassword)
                    .add(proxyPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkProxy;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField proxyAddress;
    private javax.swing.JPasswordField proxyPassword;
    private javax.swing.JSpinner proxyPort;
    private javax.swing.JTextField proxyUsername;
    // End of variables declaration//GEN-END:variables
}