/*
 * NBSortLinesPanel.java
 *
 * Created on 25 February 2008, 08:37
 */

package flapjack.gui.dialog.analysis;

import javax.swing.*;

import flapjack.data.*;

/**
 *
 * @author  imilne
 */
class NBSortLinesPanel extends javax.swing.JPanel
{
	private GTView view;

	private DefaultComboBoxModel lineModel;

	/** Creates new form NBSortLinesPanel */
	public NBSortLinesPanel(GTViewSet viewSet)
	{
		initComponents();

		view = viewSet.getSelectedView();

		lineModel = new DefaultComboBoxModel();
		for (int i = 0; i < view.getLineCount(); i++)
			lineModel.addElement(view.getLine(i));

		selectedLine.setModel(lineModel);

		if (view.mouseOverLine != -1)
			selectedLine.setSelectedIndex(view.mouseOverLine);
	}

	boolean isOK()
	{
		view.mouseOverLine = selectedLine.getSelectedIndex();

		return true;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        group2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        selectedLine = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        radioMarkersCurrent = new javax.swing.JRadioButton();
        radioMarkersAll = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setLabelFor(selectedLine);
        jLabel1.setText("Sort lines (by either similarity or locus comparison) to this line:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sort using the markers from:"));

        group1.add(radioMarkersCurrent);
        radioMarkersCurrent.setSelected(true);
        radioMarkersCurrent.setText("The current chromosome only");
        radioMarkersCurrent.setEnabled(false);

        group1.add(radioMarkersAll);
        radioMarkersAll.setText("All chromosomes in the dataset");
        radioMarkersAll.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(radioMarkersCurrent)
                    .add(radioMarkersAll))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(radioMarkersCurrent)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(radioMarkersAll))
        );

        jLabel2.setText("This dialog is a WORK IN PROGRESS placeholder.");

        jLabel3.setText("You can also select the line to use by right clicking on the canvas");

        jLabel4.setText("and selecting the sort option from the pop-up menu.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel4)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(selectedLine, 0, 309, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(selectedLine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel4)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup group1;
    private javax.swing.ButtonGroup group2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioMarkersAll;
    private javax.swing.JRadioButton radioMarkersCurrent;
    private javax.swing.JComboBox selectedLine;
    // End of variables declaration//GEN-END:variables

}
