/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jhi.flapjack.gui.dialog.analysis;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import jhi.flapjack.analysis.*;
import jhi.flapjack.data.*;
import jhi.flapjack.gui.*;

import scri.commons.gui.*;
import scri.commons.gui.SwingUtils;

/**
 *
 * @author gs40939
 */
public class PedVerStatsDialog extends JDialog implements ActionListener
{
	private boolean isOK;

	private ButtonGroup f1Group;

	private DefaultComboBoxModel<LineInfo> parent1Model;
	private DefaultComboBoxModel<LineInfo> parent2Model;
	private DefaultComboBoxModel<LineInfo> f1Model;

	/**
	 * Creates new form PedVerStatsDialogNew
	 */
	public PedVerStatsDialog(AnalysisSet as)
	{
		super(
			Flapjack.winMain,
			RB.getString("gui.dialog.analysis.CalculateSimMatrixDialog.title"),
			true
		);

		isOK = false;

        initComponents();
		initComponents2();

		setupF1ButtonGroup();
		setupComboBoxes(as);

		parentsPanel.setBackground(Color.WHITE);

		rdbSimulateF1.setSelected(true);

		getContentPane().setBackground(Color.WHITE);

		getRootPane().setDefaultButton(bOK);
		SwingUtils.addCloseHandler(this, bOK);

		pack();
		setLocationRelativeTo(Flapjack.winMain);
		setResizable(false);
		setVisible(true);
	}

	private void setupComboBoxes(AnalysisSet as)
	{
		parent1Model = createComboModelFrom(as);
		parent1Combo.setModel(parent1Model);
		if (as.lineCount() >= 1)
			parent1Combo.setSelectedIndex(0);

		parent2Model = createComboModelFrom(as);
		parent2Combo.setModel(parent2Model);
		if (as.lineCount() >= 2)
			parent2Combo.setSelectedIndex(1);

		f1Model = createComboModelFrom(as);
		f1Combo.setModel(f1Model);
		if (as.lineCount() >= 3)
			f1Combo.setSelectedIndex(2);
	}

	private DefaultComboBoxModel<LineInfo> createComboModelFrom(AnalysisSet as)
	{
		DefaultComboBoxModel<LineInfo> model = new DefaultComboBoxModel<>();
		for (int i = 0; i < as.lineCount(); i++)
			model.addElement(as.getLine(i));

		return model;
	}

	private void initComponents2()
	{
		RB.setText(bOK, "gui.text.ok");
		bOK.addActionListener(this);

		RB.setText(bCancel, "gui.text.cancel");
		bCancel.addActionListener(this);
	}

	private void setupF1ButtonGroup()
	{
		f1Group = new ButtonGroup();
		f1Group.add(rdbSelectF1);
		f1Group.add(rdbSimulateF1);
	}

	public boolean isOK()
		{ return isOK; }

	@Override
	public void actionPerformed(ActionEvent e)
	{
		if (e.getSource() == bOK)
		{
			isOK = true;
			setVisible(false);
		}

		else if (e.getSource() == bCancel)
			setVisible(false);
	}

	public LineInfo getParent1()
	{
		return (LineInfo)parent1Combo.getSelectedItem();
	}

	public LineInfo getParent2()
	{
		return (LineInfo)parent2Combo.getSelectedItem();
	}

	public LineInfo getF1()
	{
		return (LineInfo)f1Combo.getSelectedItem();
	}

	public boolean simulateF1()
	{
		return rdbSimulateF1.isSelected();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        parentsPanel = new javax.swing.JPanel();
        lblParent1 = new javax.swing.JLabel();
        parent1Combo = new javax.swing.JComboBox<>();
        lblParent2 = new javax.swing.JLabel();
        parent2Combo = new javax.swing.JComboBox<>();
        rdbSimulateF1 = new javax.swing.JRadioButton();
        rdbSelectF1 = new javax.swing.JRadioButton();
        f1Combo = new javax.swing.JComboBox<>();
        dialogPanel1 = new scri.commons.gui.matisse.DialogPanel();
        bOK = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        parentsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select parents:"));

        lblParent1.setText("Select parent 1:");
        lblParent1.setToolTipText("");

        lblParent2.setText("Select parent 2:");
        lblParent2.setToolTipText("");

        rdbSimulateF1.setText("Simulate F1 from parents (above)");

        rdbSelectF1.setText("Select F1 from existing lines:");
        rdbSelectF1.setActionCommand("");

        javax.swing.GroupLayout parentsPanelLayout = new javax.swing.GroupLayout(parentsPanel);
        parentsPanel.setLayout(parentsPanelLayout);
        parentsPanelLayout.setHorizontalGroup(
            parentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parent1Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parent2Combo, 0, 348, Short.MAX_VALUE)
                    .addGroup(parentsPanelLayout.createSequentialGroup()
                        .addGroup(parentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbSelectF1)
                            .addComponent(lblParent1)
                            .addComponent(lblParent2)
                            .addComponent(rdbSimulateF1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(f1Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        parentsPanelLayout.setVerticalGroup(
            parentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parent1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblParent2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parent2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdbSimulateF1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbSelectF1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bOK.setText("OK");
        dialogPanel1.add(bOK);

        bCancel.setText("Cancel");
        dialogPanel1.add(bCancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialogPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOK;
    private scri.commons.gui.matisse.DialogPanel dialogPanel1;
    private javax.swing.JComboBox<LineInfo> f1Combo;
    private javax.swing.JLabel lblParent1;
    private javax.swing.JLabel lblParent2;
    private javax.swing.JComboBox<LineInfo> parent1Combo;
    private javax.swing.JComboBox<LineInfo> parent2Combo;
    private javax.swing.JPanel parentsPanel;
    private javax.swing.JRadioButton rdbSelectF1;
    private javax.swing.JRadioButton rdbSimulateF1;
    // End of variables declaration//GEN-END:variables
}
