// Copyright 2009-2021 Information & Computational Sciences, JHI. All rights
// reserved. Use is subject to the accompanying licence terms.

package jhi.flapjack.gui.dialog.prefs;

import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

import jhi.flapjack.gui.*;

import scri.commons.gui.*;

class GeneralTabNB extends JPanel implements IPrefsTab
{
	private DefaultComboBoxModel<String> displayModel;
	private DefaultComboBoxModel<String> updateModel;

    public GeneralTabNB()
    {
        initComponents();

        setBackground((Color)UIManager.get("fjDialogBG"));

		// Interface settings
		generalPanel.setBorder(BorderFactory.createTitledBorder(RB.getString("gui.dialog.prefs.NBGeneralPanel.generalPanelTitle")));
		RB.setText(displayLabel, "gui.dialog.prefs.NBGeneralPanel.displayLabel");
		RB.setText(checkDecimal, "gui.dialog.prefs.NBGeneralPanel.checkDecimal");

		displayModel = new DefaultComboBoxModel<String>();
		displayModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.auto"));
		displayModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.en_GB"));
		displayModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.en_US"));
		displayModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.de_DE"));
		displayModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.es_MX"));
		displayCombo.setModel(displayModel);


		// Update settings
		RB.setText(updateLabel, "gui.dialog.prefs.NBGeneralPanel.updateLabel");

		updateModel = new DefaultComboBoxModel<String>();
		updateModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.updateNever"));
		updateModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.updateStartup"));
		updateModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.updateDaily"));
		updateModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.updateWeekly"));
		updateModel.addElement(RB.getString("gui.dialog.prefs.NBGeneralPanel.updateMonthly"));
		updateCombo.setModel(updateModel);

		initSettings();
	}

    private int getLocaleIndex()
	{
		if (Prefs.localeText.equals("en_GB"))
			return 1;
		else if (Prefs.localeText.equals("en_US"))
			return 2;
		else if (Prefs.localeText.equals("de_DE"))
			return 3;
		else if (Prefs.localeText.equals("es_MX"))
			return 4;
		else
			return 0;
	}

	private void initSettings()
    {
    	displayCombo.setSelectedIndex(getLocaleIndex());
		checkDecimal.setSelected(Prefs.guiDecimalEnglish);
    	updateCombo.setSelectedIndex(Prefs.guiUpdateSchedule);
    }

	public void applySettings()
	{
		switch (displayCombo.getSelectedIndex())
		{
			case 1:  Prefs.localeText = "en_GB"; break;
			case 2:  Prefs.localeText = "en_US"; break;
			case 3:  Prefs.localeText = "de_DE"; break;
			case 4:  Prefs.localeText = "es_MX"; break;
			default: Prefs.localeText = "auto";
		}

		Prefs.guiDecimalEnglish = checkDecimal.isSelected();
		Prefs.guiUpdateSchedule = updateCombo.getSelectedIndex();
	}

	public void setDefaults()
	{
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        generalPanel = new javax.swing.JPanel();
        displayCombo = new javax.swing.JComboBox<>();
        updateCombo = new javax.swing.JComboBox<>();
        displayLabel = new javax.swing.JLabel();
        updateLabel = new javax.swing.JLabel();
        checkDecimal = new javax.swing.JCheckBox();

        generalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General options (restart to apply):"));
        generalPanel.setOpaque(false);

        displayLabel.setLabelFor(displayCombo);
        displayLabel.setText("Interface display language:");

        updateLabel.setLabelFor(updateCombo);
        updateLabel.setText("Check for newer Flapjack versions:");

        checkDecimal.setText("Always use English decimal mark settings (eg 3.141 for pi)");

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayLabel)
                            .addComponent(updateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateCombo, 0, 258, Short.MAX_VALUE)
                            .addComponent(displayCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(checkDecimal)))
                .addContainerGap())
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayLabel)
                    .addComponent(displayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(checkDecimal)
                .addGap(18, 18, 18)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLabel)
                    .addComponent(updateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkDecimal;
    private javax.swing.JComboBox<String> displayCombo;
    private javax.swing.JLabel displayLabel;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JComboBox<String> updateCombo;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration//GEN-END:variables
}