// Copyright 2007-2010 Plant Bioinformatics Group, SCRI. All rights reserved.
// Use is subject to the accompanying licence terms.

package flapjack.gui.navpanel;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import flapjack.gui.*;

import scri.commons.gui.*;
import scri.commons.gui.matisse.HyperLinkLabel;

public class NBStartHelpPanel extends javax.swing.JPanel implements ActionListener
{
	private HyperLinkLabel[] labels = new HyperLinkLabel[8];

	private static String home =
		"http://bioinf.scri.ac.uk/flapjack/help";

    public NBStartHelpPanel()
	{
		initComponents();
		setOpaque(false);

		RB.setText(homeLabel, "gui.navpanel.NBStartHelpPanel.homeLabel");

		homeLabel.setIcon(Icons.getIcon("BOOK"));
		homeLabel.addActionListener(this);

		labels[0] = link1; labels[1] = link2;
		labels[2] = link3; labels[3] = link4;
		labels[4] = link5; labels[5] = link6;
		labels[6] = link7; labels[7] = link8;

		for (int i = 0; i < labels.length; i++)
		{
			RB.setText(labels[i], "gui.navpanel.NBStartHelpPanel.link" + (i+1));
			labels[i].addActionListener(this);
		}
    }

	public void actionPerformed(ActionEvent e)
	{
		if (e.getSource() == homeLabel)
    		FlapjackUtils.visitURL(home);
		else
		{
			for (int i = 0; i < labels.length; i++)
				if (e.getSource() == labels[i])
				{
					FlapjackUtils.visitURL(RB.getString(
							"gui.navpanel.NBStartHelpPanel.url" + (i+1)));
				}
		}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeLabel = new scri.commons.gui.matisse.HyperLinkLabel();
        link1 = new scri.commons.gui.matisse.HyperLinkLabel();
        link2 = new scri.commons.gui.matisse.HyperLinkLabel();
        link3 = new scri.commons.gui.matisse.HyperLinkLabel();
        link4 = new scri.commons.gui.matisse.HyperLinkLabel();
        link5 = new scri.commons.gui.matisse.HyperLinkLabel();
        link6 = new scri.commons.gui.matisse.HyperLinkLabel();
        link7 = new scri.commons.gui.matisse.HyperLinkLabel();
        link8 = new scri.commons.gui.matisse.HyperLinkLabel();

        homeLabel.setForeground(new java.awt.Color(68, 106, 156));
        homeLabel.setText("Visit the online Flapjack user manual");

        link1.setForeground(new java.awt.Color(68, 106, 156));
        link1.setIcon(Icons.getIcon("BUTTON"));
        link1.setText("link1");

        link2.setForeground(new java.awt.Color(68, 106, 156));
        link2.setIcon(Icons.getIcon("BUTTON"));
        link2.setText("link2");

        link3.setForeground(new java.awt.Color(68, 106, 156));
        link3.setIcon(Icons.getIcon("BUTTON"));
        link3.setText("link3");

        link4.setForeground(new java.awt.Color(68, 106, 156));
        link4.setIcon(Icons.getIcon("BUTTON"));
        link4.setText("link4");

        link5.setForeground(new java.awt.Color(68, 106, 156));
        link5.setIcon(Icons.getIcon("BUTTON"));
        link5.setText("link5");

        link6.setForeground(new java.awt.Color(68, 106, 156));
        link6.setIcon(Icons.getIcon("BUTTON"));
        link6.setText("link6");

        link7.setForeground(new java.awt.Color(68, 106, 156));
        link7.setIcon(Icons.getIcon("BUTTON"));
        link7.setText("link7");

        link8.setForeground(new java.awt.Color(68, 106, 156));
        link8.setIcon(Icons.getIcon("BUTTON"));
        link8.setText("link8");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(homeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(link1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(link2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(link3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(link4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(link5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(link6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(link7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(link8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(homeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(link1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(6, 6, 6)
                .add(link3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(6, 6, 6)
                .add(link4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(6, 6, 6)
                .add(link5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(6, 6, 6)
                .add(link6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private scri.commons.gui.matisse.HyperLinkLabel homeLabel;
    private scri.commons.gui.matisse.HyperLinkLabel link1;
    private scri.commons.gui.matisse.HyperLinkLabel link2;
    private scri.commons.gui.matisse.HyperLinkLabel link3;
    private scri.commons.gui.matisse.HyperLinkLabel link4;
    private scri.commons.gui.matisse.HyperLinkLabel link5;
    private scri.commons.gui.matisse.HyperLinkLabel link6;
    private scri.commons.gui.matisse.HyperLinkLabel link7;
    private scri.commons.gui.matisse.HyperLinkLabel link8;
    // End of variables declaration//GEN-END:variables

}