// Copyright 2009-2019 Information & Computational Sciences, JHI. All rights
// reserved. Use is subject to the accompanying licence terms.

package jhi.flapjack.gui.dialog;

import javax.swing.*;

import jhi.flapjack.data.*;
import jhi.flapjack.gui.*;

import scri.commons.gui.*;

public class FindDataSetDialog extends JDialog
{
	private Project project;
	private NavPanel navPanel;

	public FindDataSetDialog(Project project, NavPanel navPanel)
	{
		super(
			Flapjack.winMain,
			RB.getString("gui.dialog.FindDataSetDialog.title"),
			true
		);

		this.project = project;
		this.navPanel = navPanel;

		initComponents();
		initComponents2();

		FlapjackUtils.initDialog(this, bFind, bClose, true, getContentPane());
	}

	private void initComponents2()
	{
		RB.setText(bClose, "gui.text.close");
		bClose.addActionListener(e -> setVisible(false));
		bFind.addActionListener(e -> find());
	}

	private void find()
	{
		DataSet current = navPanel.getDataSetForSelection();
		int index = project.getDataSets().indexOf(current);

		String text = findText.getText();
		if (text.length() == 0)
			return;

		// Search from current to end of list...
		for (int i = index+1; i < project.getDataSets().size(); i++)
		{
			DataSet ds = project.getDataSets().get(i);

			if (ds.getName().toLowerCase().contains(text.toLowerCase()))
			{
				navPanel.selectDataSetNode(ds);
				return;
			}
		}

		// Search from zero to current...
		for (int i = 0; i < index; i++)
		{
			DataSet ds = project.getDataSets().get(i);

			if (ds.getName().toLowerCase().contains(text.toLowerCase()))
			{
				navPanel.selectDataSetNode(ds);
				return;
			}
		}

		// some message about not found
		System.out.println("not found");
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dialogPanel1 = new scri.commons.gui.matisse.DialogPanel();
        bFind = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        findText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bFind.setText("Find next");
        dialogPanel1.add(bFind);

        bClose.setText("Close");
        dialogPanel1.add(bClose);

        jLabel1.setText("Name contains:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dialogPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findText, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(findText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dialogPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bFind;
    private scri.commons.gui.matisse.DialogPanel dialogPanel1;
    private javax.swing.JTextField findText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}