package flapjack.gui.dialog;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

class NBExportDataPanel extends JPanel implements ActionListener
{
	public NBExportDataPanel(ExportDataDialog dialog)
	{
		initComponents();

		setBackground((Color)UIManager.get("fjDialogBG"));
		mapPanel.setBackground((Color)UIManager.get("fjDialogBG"));

		combo.addActionListener(this);
		combo.addItem("Tab-delimited map file");
		combo.addItem("Tab-delimited genotype file");
		actionPerformed(null);
	}

	public void actionPerformed(ActionEvent e)
	{
		boolean enableLines = combo.getSelectedIndex() == 1;
		rDatAll.setEnabled(enableLines);
		rDatSelected.setEnabled(enableLines);
		genotypeLabel.setEnabled(enableLines);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapGroup = new javax.swing.ButtonGroup();
        datGroup = new javax.swing.ButtonGroup();
        mapPanel = new javax.swing.JPanel();
        markerLabel = new javax.swing.JLabel();
        rMapAll = new javax.swing.JRadioButton();
        rMapSelected = new javax.swing.JRadioButton();
        genotypeLabel = new javax.swing.JLabel();
        rDatAll = new javax.swing.JRadioButton();
        rDatSelected = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();

        mapPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Export options:"));

        markerLabel.setText("Include map information for the following markers:");

        mapGroup.add(rMapAll);
        rMapAll.setSelected(true);
        rMapAll.setText("All markers");

        mapGroup.add(rMapSelected);
        rMapSelected.setText("Only markers I have selected");

        genotypeLabel.setText("Include genotype information for the following lines:");

        datGroup.add(rDatAll);
        rDatAll.setSelected(true);
        rDatAll.setText("All lines");

        datGroup.add(rDatSelected);
        rDatSelected.setText("Only lines I have selected");

        jLabel1.setLabelFor(combo);
        jLabel1.setText("Export file type:");

        org.jdesktop.layout.GroupLayout mapPanelLayout = new org.jdesktop.layout.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mapPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mapPanelLayout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(combo, 0, 162, Short.MAX_VALUE))
                    .add(rMapAll)
                    .add(markerLabel)
                    .add(rMapSelected)
                    .add(rDatSelected)
                    .add(rDatAll)
                    .add(genotypeLabel))
                .addContainerGap())
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mapPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(combo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(markerLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rMapAll)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rMapSelected)
                .add(18, 18, 18)
                .add(genotypeLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rDatAll)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rDatSelected)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mapPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mapPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JComboBox combo;
    private javax.swing.ButtonGroup datGroup;
    private javax.swing.JLabel genotypeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup mapGroup;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JLabel markerLabel;
    javax.swing.JRadioButton rDatAll;
    private javax.swing.JRadioButton rDatSelected;
    javax.swing.JRadioButton rMapAll;
    private javax.swing.JRadioButton rMapSelected;
    // End of variables declaration//GEN-END:variables

}