/*
 * NBSortLinesPanel.java
 *
 * Created on 25 February 2008, 08:37
 */

package flapjack.gui.dialog.analysis;

import javax.swing.*;

import flapjack.data.*;

/**
 *
 * @author  imilne
 */
class NBSortLinesPanel extends javax.swing.JPanel
{
	private GTView view;

	private DefaultComboBoxModel lineModel;

	/** Creates new form NBSortLinesPanel */
	public NBSortLinesPanel(GTViewSet viewSet)
	{
		initComponents();

		view = viewSet.getSelectedView();

		lineModel = new DefaultComboBoxModel();
		for (int i = 0; i < view.getLineCount(); i++)
			lineModel.addElement(view.getLine(i));

		selectedLine.setModel(lineModel);

		if (view.selectedLine != -1)
			selectedLine.setSelectedIndex(view.selectedLine);
	}

	boolean isOK()
	{
		view.selectedLine = selectedLine.getSelectedIndex();

		return true;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        group1 = new javax.swing.ButtonGroup();
        group2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        selectedLine = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        radioMarkersCurrent = new javax.swing.JRadioButton();
        radioMarkersAll = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        radioSortCurrent = new javax.swing.JRadioButton();
        radioSortAll = new javax.swing.JRadioButton();

        jLabel1.setDisplayedMnemonic('s');
        jLabel1.setLabelFor(selectedLine);
        jLabel1.setText("Sort lines by their similarity to this line:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sort using the markers from:"));

        group1.add(radioMarkersCurrent);
        radioMarkersCurrent.setSelected(true);
        radioMarkersCurrent.setText("The current chromosome only");

        group1.add(radioMarkersAll);
        radioMarkersAll.setText("All chromosomes in the dataset");
        radioMarkersAll.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioMarkersCurrent)
                    .addComponent(radioMarkersAll))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radioMarkersCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMarkersAll))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Apply the sort to:"));

        group2.add(radioSortCurrent);
        radioSortCurrent.setSelected(true);
        radioSortCurrent.setText("The current chromosome only");

        group2.add(radioSortAll);
        radioSortAll.setText("All chromosomes across the current view");
        radioSortAll.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioSortCurrent)
                    .addComponent(radioSortAll))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(radioSortCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSortAll))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectedLine, javax.swing.GroupLayout.Alignment.TRAILING, 0, 377, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup group1;
    private javax.swing.ButtonGroup group2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radioMarkersAll;
    private javax.swing.JRadioButton radioMarkersCurrent;
    private javax.swing.JRadioButton radioSortAll;
    private javax.swing.JRadioButton radioSortCurrent;
    private javax.swing.JComboBox selectedLine;
    // End of variables declaration//GEN-END:variables

}
